export const categories = {
	indoorFlooring: {
		name: 'Indoor flooring',
		patterns: [
			'https://via.placeholder.com/150?text=WoodFloor1',
			'https://via.placeholder.com/150?text=WoodFloor2',
			'https://via.placeholder.com/150?text=WoodFloor3',
			'https://via.placeholder.com/150?text=WoodFloor4',
			'https://via.placeholder.com/150?text=WoodFloor5',
			'https://via.placeholder.com/150?text=WoodFloor6',
			'https://via.placeholder.com/150?text=WoodFloor7',
			'https://via.placeholder.com/150?text=WoodFloor8',
			'https://via.placeholder.com/150?text=StoneFloor1',
			'https://via.placeholder.com/150?text=StoneFloor2',
			'https://via.placeholder.com/150?text=StoneFloor3',
			'https://via.placeholder.com/150?text=StoneFloor4',
			'https://via.placeholder.com/150?text=StoneFloor5',
			'https://via.placeholder.com/150?text=StoneFloor6',
			'https://via.placeholder.com/150?text=StoneFloor7',
			'https://via.placeholder.com/150?text=StoneFloor8',
			'https://via.placeholder.com/150?text=StoneFloor9',
		],
	},
	outdoorFlooring: {
		name: 'Outdoor flooring',
		patterns: [
			'https://via.placeholder.com/150?text=Grass1',
			'https://via.placeholder.com/150?text=Grass2',
			'https://via.placeholder.com/150?text=Grass3',
			'https://via.placeholder.com/150?text=Grass4',
			'https://via.placeholder.com/150?text=Grass5',
			'https://via.placeholder.com/150?text=Grass6',
			'https://via.placeholder.com/150?text=Grass7',
			'https://via.placeholder.com/150?text=Grass8',
			'https://via.placeholder.com/150?text=Grass9',
			'https://via.placeholder.com/150?text=Dirt1',
			'https://via.placeholder.com/150?text=Dirt2',
			'https://via.placeholder.com/150?text=Dirt3',
			'https://via.placeholder.com/150?text=Dirt4',
			'https://via.placeholder.com/150?text=Dirt5',
			'https://via.placeholder.com/150?text=Dirt6',
			'https://via.placeholder.com/150?text=Dirt7',
			'https://via.placeholder.com/150?text=Dirt8',
		],
	},
};
