export const categories = {
	dungeonNotation: {
		name: 'Dungeon notation',
		stamps: [
			'https://via.placeholder.com/150?text=NormalDoor',
			'https://via.placeholder.com/150?text=TrapDoor',
			'https://via.placeholder.com/150?text=TreasureChest',
			'https://via.placeholder.com/150?text=SomeStairs',
			'https://via.placeholder.com/150?text=HiddenDoor',
			'https://via.placeholder.com/150?text=LockedDoor',
			'https://via.placeholder.com/150?text=UnlockedDoor',
			'https://via.placeholder.com/150?text=HiddenTrap',
			'https://via.placeholder.com/150?text=DungeonNotation9',
			'https://via.placeholder.com/150?text=DungeonNotation10',
			'https://via.placeholder.com/150?text=DungeonNotation11',
			'https://via.placeholder.com/150?text=DungeonNotation12',
			'https://via.placeholder.com/150?text=DungeonNotation13',
			'https://via.placeholder.com/150?text=DungeonNotation14',
			'https://via.placeholder.com/150?text=DungeonNotation15',
			'https://via.placeholder.com/150?text=DungeonNotation16',
			'https://via.placeholder.com/150?text=DungeonNotation17',
		],
	},
	indoorObjects: {
		name: 'Indoor objects',
		stamps: [
			'https://via.placeholder.com/150?text=Chair',
			'https://via.placeholder.com/150?text=Table',
			'https://via.placeholder.com/150?text=Bar',
			'https://via.placeholder.com/150?text=Drink',
			'https://via.placeholder.com/150?text=FirePlace',
			'https://via.placeholder.com/150?text=CoatRack',
			'https://via.placeholder.com/150?text=PileOfWeapons',
			'https://via.placeholder.com/150?text=SomeBarrels',
			'https://via.placeholder.com/150?text=Bench',
			'https://via.placeholder.com/150?text=Barstool',
			'https://via.placeholder.com/150?text=IndoorObject11',
			'https://via.placeholder.com/150?text=IndoorObject12',
			'https://via.placeholder.com/150?text=IndoorObject13',
			'https://via.placeholder.com/150?text=IndoorObject14',
			'https://via.placeholder.com/150?text=IndoorObject15',
			'https://via.placeholder.com/150?text=IndoorObject16',
			'https://via.placeholder.com/150?text=IndoorObject17',
		],
	},
	outdoorObjects: {
		name: 'Outdoor objects',
		stamps: [
			'https://via.placeholder.com/150?text=Tree1',
			'https://via.placeholder.com/150?text=Tree2',
			'https://via.placeholder.com/150?text=Tree3',
			'https://via.placeholder.com/150?text=Shrub1',
			'https://via.placeholder.com/150?text=Shrub2',
			'https://via.placeholder.com/150?text=Shrub3',
			'https://via.placeholder.com/150?text=SomeRocks1',
			'https://via.placeholder.com/150?text=SomeRocks2',
			'https://via.placeholder.com/150?text=SomeRocks3',
			'https://via.placeholder.com/150?text=Pond1',
			'https://via.placeholder.com/150?text=Pond2',
			'https://via.placeholder.com/150?text=Pond3',
			'https://via.placeholder.com/150?text=OutdoorObject13',
			'https://via.placeholder.com/150?text=OutdoorObject14',
			'https://via.placeholder.com/150?text=OutdoorObject15',
			'https://via.placeholder.com/150?text=OutdoorObject16',
			'https://via.placeholder.com/150?text=OutdoorObject17',
		],
	},
};
